# Generated by Django 5.0.4 on 2024-05-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('profile_image', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=70)),
                ('is_admin', models.BooleanField()),
                ('website_view', models.CharField(max_length=70)),
            ],
        ),
    ]
